.TH CPRIME 7 "July 2011" "cprime 0\&.0\&.0" "C-Prime Manual"
.
.SH NAME
C-Prime \- standard library supplement for C
.
.SH DESCRIPTION
.
.SH BUGS
Please report bugs to the mailing list at \fB<cprime@googlegroups.com>\fP
.
.SH AUTHOR
Arto Bendiken <arto@bendiken.net>
.
.SH SEE ALSO
.BR libcprime (3)
