\input texinfo   @c -*-texinfo-*-
@comment %**start of header
@setfilename cprime.info
@finalout
@include version.texi
@settitle C-Prime Manual @value{VERSION}
@documentencoding UTF-8
@comment %**end of header

@dircategory Software libraries
@direntry
* C-Prime: (cprime).       A standard library supplement for C.
@end direntry

@copying
This manual is in the public domain.
Anyone is free to copy, modify, publish, use, compile, sell, or distribute
this manual for any purpose, commercial or non-commercial, and by any means.
@end copying

@titlepage
@title C-Prime
@subtitle for version @value{VERSION}, @value{UPDATED-MONTH}
@author by Arto Bendiken (@email{arto@@bendiken.net})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top C-Prime Manual
@end ifnottex

@menu
* Overview of C-Prime::
* Glossary::
* Concept Index::
* Function and Type Index::
@end menu

@comment *********************************************************************

@node Overview of C-Prime
@chapter Overview of C-Prime

C-Prime is a portable C library designed to be a useful general-purpose
supplement to the standard C library.

@section Installation
@cindex installation

@section Error Handling
@cindex error handling
@findex errno

@comment *********************************************************************
@node Glossary
@unnumbered Glossary
@table @dfn

@item application binary interface (ABI)
TODO

@item application programming interface (API)
a set of function and data structure definitions providing an interface to a
particular function library.

@item atomicity
TODO

@item big-endian
TODO

@item compare and swap (CAS)
TODO

@item endianness
whether an architecture is @emph{big-endian} or @emph{little-endian}.

@item heap
TODO

@item little-endian
TODO

@item position-independent code (PIC)
TODO

@end table
@comment *********************************************************************

@node Concept Index
@unnumbered Concept Index
@printindex cp

@comment *********************************************************************

@node Function and Type Index
@unnumbered Function and Type Index
@printindex fn

@comment *********************************************************************

@bye
